# Generated by Django 4.1 on 2022-09-02 14:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('person', '0003_rename_mosvla_monitoring_movida_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='person',
            name='Childepartment',
        ),
        migrations.RemoveField(
            model_name='person',
            name='ChilrdDepartment1',
        ),
        migrations.RemoveField(
            model_name='person',
            name='parentdepartment',
        ),
        migrations.AddField(
            model_name='person',
            name='department',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='person.childdepartment'),
        ),
    ]
