# Generated by Django 4.1 on 2022-09-02 14:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('person', '0004_remove_person_childepartment_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='department',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='person.childdepartment'),
        ),
    ]
